name = "global_chat"
main = "src/worker.js"
compatibility_date = "2024-07-08"

# 启用    nodejs_compat 以便 ECharts 库能正常工作
compatibility_flags = [ "nodejs_compat" ]

# 静态网站托管配置
[site]
bucket = "./public"

# Durable Object 绑定
[[durable_objects.bindings]]
name       = "CHAT_ROOM_DO"
class_name = "HibernatingChating"


# R2 存储桶绑定 (聊天媒体和图表共用)
[[r2_buckets]]
binding     = "R2_BUCKET"
bucket_name = "yuangs" # ✨ 请确保这是您正确的R2桶名称

[[migrations]]
tag = "v1"
new_sqlite_classes = [ "HibernatingChating" ]

# 头条相关服务---
[[durable_objects.bindings]]
name = "TOUTIAO_SERVICE_DO"
class_name = "ToutiaoServiceDO"

[[migrations]]
tag = "v2"
new_sqlite_classes = ["ToutiaoServiceDO"]
# 头条相关服务---

# 【新增】定义管理页面要检查的房间列表 
[vars]
MANAGEMENT_ROOMS_LIST = "test,future,kerry,program" # 逗号分隔的房间名
API_DOMAIN = "api.yuangs.cc"
YOUR_FLASK_PROXY_API_URL="https://api.yuangs.cc/api/toutiaopost"
YOUR_FLASK_PROXY_API_URL_ZHIHU="https://api.yuangs.cc/api/zhihu"
MAX_CONTENT_LENGTH=10000
YOUR_EXTERNAL_NEWS_API_BASE_URL = "https://newsnow.want.biz/api/s?id="

[observability.logs]
enabled = true


# 定时触发器
# Cron 规则基于 UTC 时间。北京时间 (UTC+8) 比 UTC 早 8 小时。
[triggers]
crons = [
 # 规则一: 每日问候 (北京时间 08:00 -> UTC 00:00)
 "0 0 * * *",

 # 规则二: 图表生成 (北京时间 周一至周五, #09:00-15:00 和 21:00-03:00)
 # 对应 UTC: 周一至周五, 01:00-07:00 和 13:00-19:00
 # "0 1-7,13-19 * * 1-5",

 # 规则三: 新闻获取 (同上时间段, 每10分钟一次)
# "0 1-7,13-19 * * 1-5",

 # 规则四: 期货数据 (同上时间段, 每小时的第15分钟, 用于测试)
# "*/30 1-7,13-19 * * 1-5",
# 规则五：新增: 头条内容生成 (每30分钟)
#"*/30 * * * *"
]
